-- 1) 建表
create table if not exists public.meta_sessionid (
  id bigint generated by default as identity primary key,

  ig_ds_user_id text,
  ig_session_id text,
  th_ds_user_id text not null,
  th_session_id text not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2) 自動更新 updated_at
create or replace function public.set_meta_sessionid_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_meta_sessionid_updated_at on public.meta_sessionid;

create trigger trg_meta_sessionid_updated_at
before update on public.meta_sessionid
for each row
execute function public.set_meta_sessionid_updated_at();

-- 3) 開啟 RLS
alter table public.meta_sessionid enable row level security;

-- 正式環境建議強制所有存取都走 RLS
alter table public.meta_sessionid force row level security;
